# Generated by Django 5.2.3 on 2025-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
